CREATE TABLE chats
(
    id          INTEGER PRIMARY KEY ASC,
    session_id  INTEGER NOT NULL,
    input       TEXT    NOT NULL,
    create_time INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions (id)
) STRICT;

INSERT INTO chats
VALUES (NULL, 13, 'an input', 1000);

CREATE TABLE results
(
    id                      INTEGER PRIMARY KEY ASC,
    chat_id                 INTEGER NOT NULL,
    chat_completion_id TEXT NOT NULL, -- UUID of ChatCompletion generated by upstream
    created                 INTEGER NOT NULL,
    model                   TEXT    NOT NULL,
    system_fingerprint      TEXT    NOT NULL,
    finish_reason           TEXT    NOT NULL,

    role                    TEXT    NOT NULL,
    content                 TEXT    NOT NULL,
    reasoning_content       TEXT    NOT NULL,

    prompt_tokens           INTEGER NOT NULL,
    completion_tokens       INTEGER NOT NULL,
    cached_tokens           INTEGER NOT NULL,
    reasoning_tokens        INTEGER NOT NULL,
    prompt_cache_hit_tokens INTEGER NOT NULL,

    FOREIGN KEY (chat_id) REFERENCES chats (id)
) STRICT;

INSERT INTO results
VALUES (NULL, 1, 'uuid', 2000, 'deepseek-chat', 'dev', 'stop', 'hijack', 'content', 'reason', 5, 4, 3, 2, 1);

SELECT *
FROM chats
         JOIN results r on chats.id = r.chat_id;
