### FindSessions

GET {{host}}/v1/sessions

### CreateSession

POST {{host}}/v1/sessions

> {%
    client.global.set("id", response.body);
%}

### FindSessionByID

# use CreateSession serverals times and check it exists with FindSessions

GET {{host}}/v1/sessions/{{id}}

### FindSessionByID ill-formed ID

# use CreateSession serverals times and check it exists with FindSessions

GET {{host}}/v1/sessions/4XX

### FindSessionByID not existed ID

# use CreateSession serverals times and check it exists with FindSessions

GET {{host}}/v1/sessions/404

### Chat

POST {{host}}/v1/sessions/{{id}}/chat

{
  "content": "say this is a test",
  "model": "deepseek-chat"
}

### Chat bad ID

POST {{host}}/v1/sessions/404/chat


### Chat Stream

POST {{host}}/v1/sessions/{{id}}/chat?stream=true

{
  "content": "say this is a test",
  "model": "deepseek-reasoner"
}

### v1GetBuildInfo

GET {{host}}/v1/build-info

###
