@userId=1000

### FindSessions

GET {{host}}/v2/users/{{userId}}/sessions
Token: {{token}}

### CreateSession

POST {{host}}/v2/users/{{userId}}/sessions
Token: {{token}}

> {%
    // It just exists.
    // noinspection JSUnresolvedReference
    client.global.set("scopedId", response.body.ScopedID);
%}

### v2GetSession

GET {{host}}/v2/users/{{userId}}/sessions/{{scopedId}}
Token: {{token}}

### v2PostSessionChat

POST {{host}}/v2/users/{{userId}}/sessions/{{scopedId}}/chat
Token: {{token}}

{
  "content": "say this is a test",
  "model": "deepseek-chat"
}

### v2PostSessionChatStream

POST {{host}}/v2/users/{{userId}}/sessions/{{scopedId}}/chat?stream=true
Token: {{token}}

{
  "content": "say this is a test",
  "model": "deepseek-reasoner"
}

###