@userId=1
@scopedId=2

### FindSessions

GET {{host}}/v2/users/{{userId}}/sessions

### CreateSession

POST {{host}}/v2/users/{{userId}}/sessions

> {%
    client.global.set("id", response.body);
%}

### v2GetSession

GET {{host}}/v2/users/{{userId}}/sessions/{{scopedId}}

###